name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  Go:
    name: Go Build, Test, and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          check-latest: true
          go-version: stable
      - name: Test
        run: make test
      - name: Lint
        run: make lint
